<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIS_SubjectScheduleDataLogic\SIS_SubjectScheduleDataLogic.csproj" />
    <ProjectReference Include="..\SIS_SubjectScheduleModels\SIS_SubjectScheduleModels.csproj" />
  </ItemGroup>

</Project>
